weaver/main/routes.py
from datetime import timedelta
from os import getenv, path

from flask import Blueprint, current_app, flash, redirect, render_template, request, session, url_for

import weaver.utils as utils
from weaver.extensions import db
from weaver.saml_auth.saml_auth import get_saml_user_and_groups
from weaver.token_auth.models import ApiToken


main = Blueprint('main', __name__, template_folder='templates')


# This checks for SAML auth and sets a session timeout
@main.before_request
def check_loggedin():
    session.permanent = True
    current_app.permanent_session_lifetime = timedelta(minutes=60)
    if getenv('NO_SAML') or current_app.config.get('NO_SAML'):
        return
    if not request.path.startswith("/saml") and not request.path.startswith("/status") and not session.get('saml'):
        login_url = url_for('login', next=request.url)
        return redirect(login_url)


# This checks for Cloudtoken credentials
@main.before_request
def check_cloudtoken():
    if 'credentials' in session and session['credentials'] is False:
        flash('No credentials - please authenticate with Cloudtoken', 'error')
        return
    return


# Helper functions
def set_action(action):
    utils.get_weaver_settings()
    session['action_name'] = action
    session['nice_action_name'] = utils.get_nice_action_name(action)


@main.route('/actionreadytostart')
def actionreadytostart():
    return render_template('actionreadytostart.html')


@main.route('/actionprogress/<action>')
def actionprogress(action):
    flash(f"Action '{action}' on {request.args.get('stack')} has begun", 'success')
    return render_template('actionprogress.html')


@main.route('/setregion/<region>')
def setregion(region):
    session['region'] = region
    session['stacks'] = utils.get_stacks()
    flash(f'Region selected: {region}', 'success')
    return redirect(request.referrer)


# Main landing page
@main.route('/')
def index():
    utils.get_weaver_settings()
    session['action_name'] = ''
    session['nice_action_name'] = ''
    return render_template('index.html')


# Action UI pages
@main.route('/upgrade', methods=['GET'])
def upgrade():
    set_action('upgrade')
    return render_template('upgrade.html')


@main.route('/clone', methods=['GET'])
def clone():
    set_action('clone')
    return render_template('clone.html')


@main.route('/fullrestart', methods=['GET'])
def fullrestart():
    set_action('fullrestart')
    return render_template('fullrestart.html')


@main.route('/rollingrestart', methods=['GET'])
def rollingrestart():
    set_action('rollingrestart')
    return render_template('rollingrestart.html')


@main.route('/ec2rollingreboot', methods=['GET'])
def ec2rollingreboot():
    set_action('ec2rollingreboot')
    return render_template('ec2rollingreboot.html')


@main.route('/restartnode', methods=['GET'])
def restartnode():
    set_action('restartnode')
    return render_template('restartnode.html')


@main.route('/togglenode', methods=['GET'])
def togglenode():
    set_action('togglenode')
    return render_template('togglenode.html')


@main.route('/rollingrebuild', methods=['GET'])
def rollingrebuild():
    set_action('rollingrebuild')
    return render_template('rollingrebuild.html')


@main.route('/rollingreinit', methods=['GET'])
def rollingreinit():
    set_action('rollingreinit')
    return render_template('rollingreinit.html')


@main.route('/create', methods=['GET'])
def create():
    set_action('create')
    return render_template('create.html')


@main.route('/destroy', methods=['GET'])
def destroy():
    set_action('destroy')
    return render_template('destroy.html')


@main.route('/update', methods=['GET'])
def update():
    set_action('update')
    return render_template('update.html')


@main.route('/viewlog', methods=['GET'])
def viewlog():
    set_action('viewlog')
    return render_template('viewlog.html')


@main.route('/syslog', methods=['GET'])
def syslog():
    set_action('syslog')
    return render_template('syslog.html')


@main.route('/diagnostics', methods=['GET'])
def diagnostics():
    set_action('diagnostics')
    return render_template('diagnostics.html')


@main.route('/runsql', methods=['GET'])
def runsql():
    set_action('runsql')
    return render_template('runsql.html')


@main.route('/admin', methods=['GET'])
def admin():
    set_action('admin')
    return render_template('admin.html')


@main.route('/admin/<stack_name>', methods=['GET'])
def admin_stack(stack_name):
    set_action('admin')
    return render_template('admin.html', stackToAdmin=stack_name)


@main.route('/token', methods=['GET'])
def token():
    set_action('token')
    tokens = db.session.execute(
        db.select(ApiToken).filter_by(token_type="refresh", revoked=False, user_name=get_saml_user_and_groups()[0]).order_by(ApiToken.created_at.desc())  # type: ignore[attr-defined]  # nosec B106
    ).scalars()
    return render_template('token_admin.html', tokens=tokens)


# function to get last modified time of JS files to automatically invalidate them when updated
@main.context_processor
def utility_processor():
    def get_filename_with_last_update_time(file_with_path):
        mtime = str(path.getmtime(path.join(current_app.root_path, file_with_path)))
        return f"/{file_with_path}?v={mtime}"

    return dict(get_filename_with_last_update_time=get_filename_with_last_update_time, get_nice_action_name=utils.get_nice_action_name)

weaver/templates/clone.html
{% extends "template-params.html" %}

{% block descriptionPanel %}
<p>Create a clone of an instance from database and filesystem snapshots. This will first destroy the stack if one exists by the name entered for the clone, then create a new stack from the selected snapshots. If there is a SQL file to run against clones of the instance being cloned, or a SQL file for stacks of this name, they will be run once the service is up, and a restart will be performed. See Run SQL for more information.</p>
{% endblock descriptionPanel %}

{% block stackSelectorDescription %}
Select stack to clone
{% endblock stackSelectorDescription %}

{% block stackStatusPanel %}
{% endblock stackStatusPanel %}

{% block extraActionsDropdownItems %}
<aui-item-link id="getCloneDefaults-button" disabled>Get clone defaults</aui-item-link>
{{ super() }}
{% endblock extraActionsDropdownItems %}

{% block extraParams %}
<div id="clone-params" style="display: none;">
    <div class="field-group param-field-group" id="stack-name-input">
        <label for="StackNameVal" class="paramLbl">Stack Name</label>
        <input class="text" type="text" name="StackNameVal" id="StackNameVal"
               data-aui-validation-field required pattern="[a-zA-Z][-a-zA-Z0-9]*"
               maxlength={{ session['stackname_length'] }}
               data-aui-validation-pattern-msg="Stack name must be a max of {{ session['stackname_length'] }} chars and satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*"/>
    </div>
    <div class="field-group param-field-group">
        <label for="RegionVal" class="paramLbl">Region</label>
        <select id="RegionVal" name="RegionVal">
            {% for region in session['regions'] %}
            <option value="{{ region[0] }}" {% if loop.first == true %}selected {% endif %}>{{ region[0] }}</option>
            {% endfor %}
        </select>
    </div>
</div>
{% endblock extraParams %}

{% block buttonText %}Clone{% endblock buttonText %}

{% block scripts %}
{{ super() }}
<script src="{{ get_filename_with_last_update_time('static/js/clone.js') }}"></script>
{% endblock scripts %}

weaver/templates/create.html
{% extends "template-params.html" %}

{% block descriptionPanel %}
<p>Create new instances of Confluence, Crowd or Jira</p>
<p>Bitbucket support is currently being implemented and may not work as expected yet</p>
{% endblock descriptionPanel %}

{% block stackSelector %}
{% endblock stackSelector %}

{% block stackStatusPanel %}
{% endblock stackStatusPanel %}

{% block productSelector %}
<a id="productSelector" href="#productSelection" aria-owns="productSelection" aria-haspopup="true"
   class="aui-button aui-style-default aui-dropdown2-trigger">
    Select Product
</a>
<!-- Product dropdown -->
<div id="productSelection" class="aui-style-default aui-dropdown2">
    <ul class="aui-list-truncate">
        {% for product in session['products'] %}
        <li><a class="selectProductOption">{{ product }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock productSelector %}

{% block extraParams %}
<div class="field-group param-field-group" id="stack-name-input">
    <label for="StackNameVal" class="paramLbl">Stack Name</label>
    <input class="text" type="text" name="StackNameVal" id="StackNameVal"
           data-aui-validation-field required pattern="[a-zA-Z][-a-zA-Z0-9]*"
           maxlength={{ session['stackname_length'] }}
           data-aui-validation-pattern-msg="Stack name must be a max of {{ session['stackname_length'] }} chars and satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*">
</div>
{% endblock extraParams %}

{% block buttonText %}Create{% endblock buttonText %}

{% block scripts %}
{{ super() }}
<script src="{{ get_filename_with_last_update_time('static/js/create.js') }}"></script>
{% endblock scripts %}

weaver/templates/ec2rollingreboot.html
{% extends "page-content.html" %}

{% block descriptionPanel %}
<p>Reboot all EC2 nodes in a cluster or auto scaling group one by one. This action shuts down the product, and then issues <code>systemctl reboot</code> to the underlying EC2 node.</p>
<p>NB: If there is only one node in the cluster or auto scaling group, this action will result in downtime.</p>
<p>Any unhealthy nodes in the cluster will be rebooted before healthy nodes. Weaver will wait for each node to respond on /status and be registered in the load balancer before beginning to reboot the next node.</p>
{% endblock descriptionPanel %}

{% block extraInput %}
{% block asgSelector %}
<a id="asgSelector" href="#asgSelection" aria-owns="asgSelection" aria-haspopup="true" class="aui-button aui-style-default aui-dropdown2-trigger">
    Select ASG
</a>
<!-- ASG dropdown -->
<div id="asgSelection" class="aui-style-default aui-dropdown2">
    <ul class="aui-list-truncate" id="asgList"></ul>
</div>
{% endblock asgSelector %}
{% endblock extraInput %}

{% block mainFlexContent %}
<form class="aui">
    <fieldset class="group">
        <legend><span>Options</span></legend>
        <div id="drainOptionsDiv">
            <div class="checkbox">
                <input class="checkbox" type="checkbox" name="drainNodes" id="drainNodes" disabled checked>
                <label for="drainNodes">Drain nodes from the load balancer(s) before restarting. NB: Only works for ELBV2/NLB load balancers, and will cause the restart to be slower.</label>
            </div>
            <div class="radio">
                <input class="radio" type="radio" name="drainType" id="full" value="DEFAULT" checked="checked">
                <label for="full">Full drain</label>
            </div>
            <div class="radio" id="fastNodeDrainDiv">
                <input class="radio" type="radio" name="drainType" id="fast" value="FAST">
                <label for="fast">Fast drain</label>
            </div>
        </div>
    </fieldset>
</form>
{% endblock mainFlexContent %}

{% block buttonText %}Rolling EC2 Node Reboot{% endblock buttonText %}

{% block scripts %}
{{ super() }}
<script src="{{ get_filename_with_last_update_time('static/js/ec2rollingreboot.js') }}"></script>
{% endblock scripts %}

weaver/templates/index.html
{% extends "layout.html" %}

{% block content %}
    <img class="hero" src="/static/img/Atlassian-vertical-blue@2x-rgb.png">
{% endblock %}

weaver/templates/page-content.html
{% extends "layout.html" %}

{% block content %}

    <div id="descriptionPanel" class="aui-item">
        {% block descriptionPanel %}
        {% endblock descriptionPanel %}
    </div>

    {% block stackSelector %}
    {#  Stack selector  #}
    <a id="stackSelector" href="#stackSelection" aria-owns="stackSelection" aria-haspopup="true"
       class="aui-button aui-style-default aui-dropdown2-trigger">
        {% block stackSelectorDescription %}
        Select Stack
        {% endblock stackSelectorDescription %}
    </a>

    <!-- Dropdown -->
    <div id="stackSelection" class="aui-style-default aui-dropdown2">
        <ul class="aui-list-truncate">
            {% for stack in session['stacks'] %}
            <li><a class="selectStackOption">{{ stack }}</a></li>
            {% endfor %}
        </ul>
    </div>
    {% endblock stackSelector %}

    {% block extraInput %}
        {% block productSelector %}
        {% endblock productSelector %}
        {% block templateSelector %}
        {% endblock templateSelector %}
        {% block asgSelector %}
        {% endblock asgSelector %}
        {% block nodeSelector %}
        {% endblock nodeSelector %}
        {% block extraActionsDropdown %}
        {% endblock extraActionsDropdown %}
    {% endblock extraInput %}

    <div class="page-container-flex">
        <div class="page-container-flex-buffer"></div>

        <div class="page-container-flex-primary">
        {% block mainFlexContent %}
            {% block Parameters %}
            {% endblock Parameters %}
            {% block progress %}
            {% endblock progress %}
        {% endblock mainFlexContent %}
        </div>

        <div class="page-container-flex-buffer"></div>

        <div class="page-container-flex-secondary">
        {% block secondaryFlexContent %}
            {#    Current Status Panel    #}
            {% block stackStatusPanel %}
            <div id="stackPanel">
                <section class="aui-page-notification aui-page-size-medium aui-page-panel aui-page-panel-content"  style="text-align: left">
                    <h3 id="stackName"></h3>
                    <div id="pleaseSelectStackMsg" class="aui-page-notification-description">
                        <p>Please select a stack to see it's current information</p>
                    </div>
                    <div id="stackInformation">
                        <p id="product">Product: </p>
                        <p id="stackState">Stack state: </p>
                        <p id="serviceStatus">Service status: </p>
                        <p id="currentAction">Action in progress: </p>
                        <p id="currentVersion">Current version: </p>
                        <h4 id="nodesHeader">Nodes (<span id="nodesCount">0</span>):</h4>
                        <div id="nodes"></div>
                    </div>
                </section>
            </div>
            {% endblock stackStatusPanel %}
            {% block gitRepoStatusPanel %}
            {% endblock gitRepoStatusPanel %}
        {% endblock secondaryFlexContent %}
        </div>

        <div class="page-container-flex-buffer"></div>

    </div>

{% block button %}
{#  Button to perform page action  #}
<div class="aui-group">
    <button id="action-button" type="submit" class="aui-button aui-button-primary" aria-disabled="true">
        {% block buttonText %}Ok{% endblock buttonText %}
    </button>
</div>
{% endblock button %}

<!-- -->
<!-- Modal prompts -->
<!-- All close on OK and Cancel by default -->
<!-- -->

<!-- Modal auth prompt -->
<section id="modal-auth-dialog" class="aui-dialog2 aui-dialog2-large aui-layer" data-aui-modal="true" role="dialog" hidden>
    <header class="aui-dialog2-header">
        <h2 class="aui-dialog2-header-main" id="modal-auth-title">{% block modalAuthTitle %}Authentication{% endblock modalAuthTitle %}</h2>
        <a class="aui-dialog2-header-close">
            <span class="aui-icon aui-icon-small aui-iconfont-close-dialog">Close</span>
        </a>
    </header>
    <div class="aui-dialog2-content" id="modal-auth-contents">
        {% block modalAuthContents %}
            {% block modalAuthDesc %}
                <p>This action requires admin authentication within the product.<br><br></p>
            {% endblock modalAuthDesc %}
            {% block modalAuthPanel %}
            <p>NB: We do NOT recommend entering your credentials unless both Weaver and the product use SSL.<br><br>
                Please enter your administrator Personal Access Token:</p>
            <form class="aui top-label">
                <fieldset class="top-label">
                    <div class="field-group">
                        <label for="personal_access_token">Personal Access Token</label>
                        <input class="password" type="password" id="personal_access_token" name="personal_access_token">
                    </div>
                </fieldset>
            </form>
            {% endblock modalAuthPanel %}
        {% endblock modalAuthContents %}
    </div>
    <footer class="aui-dialog2-footer">
        <div class="aui-dialog2-footer-actions">
            <button class="aui-button aui-button-primary" id="modal-auth-ok-btn" onclick="AJS.dialog2('#modal-auth-dialog').hide();">Okay</button>
            <button class="aui-button aui-button-link" id="modal-auth-cancel-btn" onclick="AJS.dialog2('#modal-auth-dialog').hide();">Cancel</button>
        </div>
    </footer>
</section>

<!-- Modal changeset prompt -->
<section id="modal-changeset-dialog" class="aui-dialog2 aui-dialog2-xlarge aui-layer" data-aui-modal="true" role="dialog" hidden>
    <header class="aui-dialog2-header">
        <h2 class="aui-dialog2-header-main" id="modal-changeset-title">{% block modalChangesetTitle %}Changeset Details - <span id="changesetName"></span>{% endblock modalChangesetTitle %}</h2>
        <a class="aui-dialog2-header-close">
            <span class="aui-icon aui-icon-small aui-iconfont-close-dialog">Close</span>
        </a>
    </header>
    <div class="aui-dialog2-content" id="modal-changeset-contents">
        {% block modalChangesetContents %}
        <div id="changesetDescription">
            <p>The following changes will be made to stack <strong><span id="changesetStackname"></span></strong>; please review and confirm you wish to proceed.</p>
            <div id='changesetDeletionWarning' class="aui-message aui-message-warning">
                <p class="title">Review this changeset carefully!</p>
                <p>This changeset includes replacement and/or deletion of some resources; proceed with caution.</p>
            </div>
            <table class="aui">
                <thead>
                <tr>
                    <th id="resource-id">Id</th>
                    <th id="resource-type">Type</th>
                    <th id="resource-action">Action</th>
                    <th id="resource-scope">Scope</th>
                    <th id="resource-replacment">Replacement</th>
                </tr>
                </thead>
                <tbody/>
            </table>
        </div>
        {% endblock modalChangesetContents %}
    </div>
    <footer class="aui-dialog2-footer">
        <div class="aui-dialog2-footer-actions">
            <button class="aui-button aui-button-primary" id="modal-changeset-ok-btn" onclick="AJS.dialog2('#modal-changeset-dialog').hide();">Execute Changeset</button>
            <button class="aui-button aui-button-link" id="modal-changeset-cancel-btn" onclick="AJS.dialog2('#modal-changeset-dialog').hide();">Cancel</button>
        </div>
        <div class="aui-dialog2-footer-hint">
            <div id="fastNodeDrainDiv" style="display:none">
                <input class="checkbox" type="checkbox" id="fastNodeDrainCheckbox" name="fastNodeDrainCheckbox">
                <label for="fastNodeDrainCheckbox" id="fastNodeDrainLabel">Fast node drain</label><br>
            </div>
        </div>
    </footer>
</section>

<!-- Modal confirmation prompt -->
<section id="modal-confirm-dialog" class="aui-dialog2 aui-dialog2-medium aui-layer" data-aui-modal="true" role="dialog" hidden>
    <header class="aui-dialog2-header">
        <h2 class="aui-dialog2-header-main" id="modal-confirm-title">{% block modalConfirmTitle %}Confirm{% endblock modalConfirmTitle %}</h2>
        <a class="aui-dialog2-header-close">
            <span class="aui-icon aui-icon-small aui-iconfont-close-dialog">Close</span>
        </a>
    </header>
    <div class="aui-dialog2-content" id="modal-confirm-contents">
        {% block modalConfirmContents %}
            {% block modalConfirmDesc %}
                Are you sure you want to perform this action?
            {% endblock modalConfirmDesc %}
        {% endblock modalConfirmContents %}
    </div>
    <footer class="aui-dialog2-footer">
        <div class="aui-dialog2-footer-actions">
            <button class="aui-button aui-button-primary" id="modal-confirm-ok-btn" onclick="AJS.dialog2('#modal-confirm-dialog').hide();">{% block modalConfirmBtnName %}Okay{% endblock modalConfirmBtnName %}</button>
            <button class="aui-button aui-button-link" id="modal-confirm-cancel-btn" onclick="AJS.dialog2('#modal-confirm-dialog').hide();">Cancel</button>
        </div>
    </footer>
</section>

<!-- Modal error dialog -->
<section id="modal-error-dialog" class="aui-dialog2 aui-dialog2-medium aui-layer" data-aui-modal="true" role="dialog" hidden>
    <header class="aui-dialog2-header">
        <h2 class="aui-dialog2-header-main" id="modal-error-title">{% block modalErrorTitle %}Whoops{% endblock modalErrorTitle %}</h2>
        <a class="aui-dialog2-header-close">
            <span class="aui-icon aui-icon-small aui-iconfont-close-dialog">Close</span>
        </a>
    </header>
    <div class="aui-dialog2-content">
        <div class="aui-message aui-message-error" id="modal-error-contents">
            {% block modalErrorContents %}
                {% block modalErrorDesc %}
                    Something has gone wrong
                {% endblock modalErrorDesc %}
            {% endblock modalErrorContents %}
        </div>
    </div>
    <footer class="aui-dialog2-footer">
        <div class="aui-dialog2-footer-actions">
            <button class="aui-button aui-button-primary" id="modal-error-ok-btn" onclick="AJS.dialog2('#modal-error-dialog').hide();">Okay</button>
        </div>
    </footer>
</section>

<!-- Modal progress dialog -->
<section id="modal-progress-dialog" class="aui-dialog2 aui-dialog2-small aui-layer" data-aui-modal="true" role="dialog" hidden>
    <header class="aui-dialog2-header">
        <h2 class="aui-dialog2-header-main" id="modal-progress-title">{% block modalProgressTitle %}Please wait{% endblock modalProgressTitle %}</h2>
        <a class="aui-dialog2-header-close">
            <span class="aui-icon aui-icon-small aui-iconfont-close-dialog">Close</span>
        </a>
    </header>
    <div class="aui-dialog2-content" id="modal-progress-contents">
        {% block modalProgressContents %}
            {% block modalProgressDesc %}
                <p><aui-progressbar indeterminate></aui-progressbar></p>
        {% endblock modalProgressDesc %}
        {% endblock modalProgressContents %}
    </div>
    <footer class="aui-dialog2-footer">
        <div class="aui-dialog2-footer-actions">
            <button class="aui-button aui-button-link" id="modal-progress-cancel-btn" onclick="AJS.dialog2('#modal-progress-dialog').hide();">Cancel</button>
        </div>
    </footer>
</section>
{% endblock content%}

weaver/templates/rollingrebuild.html
{% extends "page-content.html" %}

{% block extraInput %}
{% block asgSelector %}
<a id="asgSelector" href="#asgSelection" aria-owns="asgSelection" aria-haspopup="true" class="aui-button aui-style-default aui-dropdown2-trigger">
    Select ASG
</a>
<!-- ASG dropdown -->
<div id="asgSelection" class="aui-style-default aui-dropdown2">
    <ul class="aui-list-truncate" id="asgList"></ul>
</div>
{% endblock asgSelector %}
{% endblock extraInput %}

{% block descriptionPanel %}
<p>Destroy and rebuild all nodes in a cluster or auto scaling group, one at a time. Nodes will be drained from the load balancer(s) before being terminated.</p>
{% endblock descriptionPanel %}

{% block mainFlexContent %}
<form class="aui">
    <fieldset class="group">
        <legend><span>Options</span></legend>
        <div id="drainOptionsDiv">
            <div class="checkbox">
                <input class="checkbox" type="checkbox" name="drainNodes" id="drainNodes" disabled checked>
                <label for="drainNodes">Drain nodes from the load balancer(s) before restarting. NB: Only works for ELBV2/NLB load balancers, and will cause the restart to be slower.</label>
            </div>
            <div class="radio">
                <input class="radio" type="radio" name="drainType" id="full" value="default" checked="checked">
                <label for="full">Full drain</label>
            </div>
            <div class="radio" id="fastNodeDrainDiv">
                <input class="radio" type="radio" name="drainType" id="fast" value="fast">
                <label for="fast">Fast drain</label>
            </div>
        </div>
    </fieldset>
</form>
{% endblock mainFlexContent %}

{% block modalAuthTitle %}Check index health?{% endblock modalAuthTitle %}
{% block modalAuthDesc %}
    <p>Should Weaver to wait until the index health on each node before proceeding?
        This allows each new node time to request and restore an index snapshot from a running node.<br><br>
        If yes, enter administrator credentials below. If these fields are left blank, index health will NOT be checked.<br><br></p>
{% endblock modalAuthDesc %}

{% block modalConfirmTitle %}Index will not be restored{% endblock modalConfirmTitle %}
{% block modalConfirmDesc %}
    This stack only has one node, so the index will not be automatically restored on the new node.
    An administrator will have to log in and restore the index from snapshot manually.
{% endblock modalConfirmDesc %}

{% block buttonText %}Rolling Rebuild{% endblock buttonText %}

{% block scripts %}
{{ super() }}
<script src="{{ get_filename_with_last_update_time('static/js/rebuild.js') }}"></script>
{% endblock scripts %}

weaver/templates/rollingreinit.html
{% extends "page-content.html" %}

{% block descriptionPanel %}
<p>Re-initialize cluster nodes by re-executing cfn-init, one at a time. Nodes will be drained from the load balancer before being re-initialized.</p>
{% endblock descriptionPanel %}

{% block mainFlexContent %}
<form class="aui">
    <fieldset class="group">
        <legend><span>Options</span></legend>
        <div id="drainOptionsDiv">
            <div class="checkbox">
                <input class="checkbox" type="checkbox" name="drainNodes" id="drainNodes" disabled checked>
                <label for="drainNodes">Drain nodes from the load balancer(s) before restarting. NB: Only works for ELBV2/NLB load balancers, and will cause the restart to be slower.</label>
            </div>
            <div class="radio">
                <input class="radio" type="radio" name="drainType" id="full" value="default" checked="checked">
                <label for="full">Full drain</label>
            </div>
            <div class="radio" id="fastNodeDrainDiv">
                <input class="radio" type="radio" name="drainType" id="fast" value="fast">
                <label for="fast">Fast drain</label>
            </div>
        </div>
    </fieldset>
</form>
{% endblock mainFlexContent %}

{% block buttonText %}Rolling Re-init{% endblock buttonText %}

{% block scripts %}
{{ super() }}
<script src="{{ get_filename_with_last_update_time('static/js/reinit.js') }}"></script>
{% endblock scripts %}

weaver/templates/update.html
{% extends "template-params.html" %}

{% block buttonText %}Update{% endblock buttonText %}

{% block scripts %}
{{ super() }}
<script src="{{ get_filename_with_last_update_time('static/js/update.js') }}"></script>
{% endblock scripts %}

weaver/templates/viewlog.html
{% extends "page-content.html" %}

{% block descriptionPanel %}
<p>View the logs for the most recent action performed against a given stack.</p>
{% endblock descriptionPanel %}

{% block progress %}
<div class="aui-group">
    {#    Progress Panel    #}
    <iframe id="log" src="{{ url_for('main.actionreadytostart') }}" height="400">
        Cannot display status because browser does not support iframes.
    </iframe>
</div>
{% endblock progress %}

{% block scripts %}
{{ super() }}
<script src="{{ get_filename_with_last_update_time('static/js/actionprogress.js') }}"></script>
<script src="{{ get_filename_with_last_update_time('static/js/viewlog.js') }}"></script>
{% endblock scripts %}